---
sudo: false

services:
  - docker

language: scala

scala: tip

script:
  - ./scripts/google.sh
  - docker build -t google-extractor .
  - docker run --rm --name google-extractor google-extractor

notifications:
  on_success: always
  email: false
  slack:
    secure: "S/peey3kWylUlpinP8j/2//rYM86cE5p71OsvD/A4Cx8EG07F5OaCvybVuO4GYhDextvgP/JhSO1faTh/nzSlr2zVWG3j0WOY8Fmhly5sQY3A5mkcBoE3jlu4Y4jk2EDs/wJXFcHb+g2MUC6h36/PnbhQore6InkcO49bgiI1/JKu1ehX1b7bG70lHZDhi1o6SYSaHYEAnotmRiCq5EPFTuFHHRpo14Y9ADuJjiRTFzB4han2KO1ACtpFT3Ub9MLZSUxRPGNKTCwnz9g7+AcsLkiydk2qXbUDTdRTEPB0sUNtUCqHFM0CLY3W/9IQP90exxoFe/jJqekvlZbl9aU8gRx33H1eQKQsxKiGjmtcGr7CpVnExANg7mbj4PWgXb7e+XiU42L4iYYUJkEJ+UQgvhgszMKYoLMwj4jr2caK7dLmHV90QbuBTuyr6RujVkcpIED5q+iRBvta8k1L3TMrX72nOgpJNUqH7or4CI+iEkfjXUcHLjwnEEl9W2G9GiJ4S6bUrRZ9rrEMBQltp7kqrd/Hqy0cxQkFEDLcCbWIzBeNqlYtJElcExFKNxhbhQQejEdF5b6samHrDe8v/h8mtKCgwT6vhXQZEBI8IgcR1fyU1VRORS9Hp+myDV/xzR+oOGtPrh5LLkuJzgAXH/UnP+4pcS46FJVGAVLYFNRBEk="
...
